/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 30-lis-2024 19:04:21 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Lesson` CASCADE
;

DROP TABLE IF EXISTS `Room` CASCADE
;

DROP TABLE IF EXISTS `Teacher` CASCADE
;

DROP TABLE IF EXISTS `Timeslot` CASCADE
;

DROP TABLE IF EXISTS `Timetable` CASCADE
;

/* Create Tables */

CREATE TABLE `Lesson`
(
	`Id` varchar(0) NULL,
	`Room` varchar(0) NULL,
	`Studentgroup` varchar(0) NULL,
	`Subject` varchar(0) NULL,
	`Teacher` varchar(0) NULL,
	`Timeslot` varchar(0) NULL,
	`LessonID` varchar(0) NOT NULL,
	`TimetableID` varchar(0) NULL,
	`TeacherID` varchar(0) NULL,
	`TimeslotID` varchar(0) NULL,
	`RoomID` varchar(0) NULL,
	CONSTRAINT `PK_Lesson` PRIMARY KEY (`LessonID` ASC)
)

;

CREATE TABLE `Room`
(
	`Id` varchar(0) NULL,
	`Name` varchar(0) NULL,
	`RoomID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Room` PRIMARY KEY (`RoomID` ASC)
)

;

CREATE TABLE `Teacher`
(
	`Id` varchar(0) NULL,
	`Name` varchar(0) NULL,
	`TeacherID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Teacher` PRIMARY KEY (`TeacherID` ASC)
)

;

CREATE TABLE `Timeslot`
(
	`Dayofweek` varchar(0) NULL,
	`Endtime` varchar(0) NULL,
	`Id` varchar(0) NULL,
	`Starttime` varchar(0) NULL,
	`TimeslotID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Timeslot` PRIMARY KEY (`TimeslotID` ASC)
)

;

CREATE TABLE `Timetable`
(
	`Lessons` varchar(0) NULL,
	`Name` varchar(0) NULL,
	`Rooms` varchar(0) NULL,
	`Score` varchar(0) NULL,
	`Solverstatus` varchar(0) NULL,
	`Timeslots` varchar(0) NULL,
	`TimetableID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Timetable` PRIMARY KEY (`TimetableID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Lesson` 
 ADD CONSTRAINT `FK_Lesson_Timetable`
	FOREIGN KEY (`TimetableID`) REFERENCES `Timetable` (`TimetableID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Lesson` 
 ADD CONSTRAINT `FK_Lesson_who?`
	FOREIGN KEY (`TeacherID`) REFERENCES `Teacher` (`TeacherID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Lesson` 
 ADD CONSTRAINT `FK_Lesson_when?`
	FOREIGN KEY (`TimeslotID`) REFERENCES `Timeslot` (`TimeslotID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Lesson` 
 ADD CONSTRAINT `FK_Lesson_where?`
	FOREIGN KEY (`RoomID`) REFERENCES `Room` (`RoomID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
