@startuml
class org.springframework.samples.petclinic.model.BaseEntity {
- Integer id
+ Integer getId()
+ void setId(Integer)
+ boolean isNew()
}


java.io.Serializable <|.. org.springframework.samples.petclinic.model.BaseEntity
@enduml