INSERT INTO docs VALUES (default, 'Jan', 'Cybulski');
INSERT INTO docs VALUES (default, 'Helena', 'Lewandowska');
INSERT INTO docs VALUES (default, 'Jan', 'Kowalski');
INSERT INTO docs VALUES (default, 'Anna', 'Nowak');
INSERT INTO docs VALUES (default, 'Piotr', 'Wiśniewski');
INSERT INTO docs VALUES (default, 'Maria', 'Wójcik');
INSERT INTO docs VALUES (default, 'Andrzej', 'Kowalczyk');
INSERT INTO docs VALUES (default, 'Katarzyna', 'Kamińska');
INSERT INTO docs VALUES (default, 'Tomasz', 'Lewandowski');
INSERT INTO docs VALUES (default, 'Małgorzata', 'Zielińska');
INSERT INTO docs VALUES (default, 'Paweł', 'Szymański');
INSERT INTO docs VALUES (default, 'Agata', 'Woźniak');
INSERT INTO docs VALUES (default, 'Marcin', 'Dąbrowski');
INSERT INTO docs VALUES (default, 'Joanna', 'Kozłowska');
INSERT INTO docs VALUES (default, 'Krzysztof', 'Jankowski');
INSERT INTO docs VALUES (default, 'Monika', 'Mazur');
INSERT INTO docs VALUES (default, 'Michał', 'Mazur');
INSERT INTO docs VALUES (default, 'Bartosz', 'Kwiatkowski');
INSERT INTO docs VALUES (default, 'Magdalena', 'Krawczyk');
INSERT INTO docs VALUES (default, 'Adam', 'Pawlak');
INSERT INTO docs VALUES (default, 'Natalia', 'Michalska');
INSERT INTO docs VALUES (default, 'Rafał', 'Sikora');
INSERT INTO docs VALUES (default, 'Kamil', 'Sikorski');
INSERT INTO docs VALUES (default, 'Karolina', 'Nowicka');
INSERT INTO docs VALUES (default, 'Michał', 'Adamczyk');
INSERT INTO docs VALUES (default, 'Aleksandra', 'Dudek');
INSERT INTO docs VALUES (default, 'Grzegorz', 'Nowakowski');
INSERT INTO docs VALUES (default, 'Ewa', 'Zając');
INSERT INTO docs VALUES (default, 'Tadeusz', 'Wieczorek');
INSERT INTO docs VALUES (default, 'Iwona', 'Jabłońska');
INSERT INTO docs VALUES (default, 'Rafał', 'Król');
INSERT INTO docs VALUES (default, 'Patrycja', 'Piotrowska');
INSERT INTO docs VALUES (default, 'Wojciech', 'Marciniak');
INSERT INTO docs VALUES (default, 'Dorota', 'Wróbel');
INSERT INTO docs VALUES (default, 'Kamil', 'Kaczmarek');
INSERT INTO docs VALUES (default, 'Marzena', 'Witkowska');
INSERT INTO docs VALUES (default, 'Łukasz', 'Kowalewski');
INSERT INTO docs VALUES (default, 'Alicja', 'Majewska');
INSERT INTO docs VALUES (default, 'Robert', 'Grabowski');
INSERT INTO docs VALUES (default, 'Joanna', 'Olszewska');
INSERT INTO docs VALUES (default, 'Kamil', 'Jaworski');
INSERT INTO docs VALUES (default, 'Anna', 'Chmielewska');
INSERT INTO docs VALUES (default, 'Tomasz', 'Zakrzewski');
INSERT INTO docs VALUES (default, 'Aleksandra', 'Sawicka');
INSERT INTO docs VALUES (default, 'Dariusz', 'Rutkowski');
INSERT INTO docs VALUES (default, 'Sylwia', 'Górska');
INSERT INTO docs VALUES (default, 'Artur', 'Tomczyk');

INSERT INTO specialties VALUES (default, 'Anestezjolog');
INSERT INTO specialties VALUES (default, 'Chirurg');
INSERT INTO specialties VALUES (default, 'Chirurg plastyczny');
INSERT INTO specialties VALUES (default, 'Chirurgia dziecięca');
INSERT INTO specialties VALUES (default, 'Chirurgia kardio-torakochirurgiczna');
INSERT INTO specialties VALUES (default, 'Chirurgia klatki piersiowej');
INSERT INTO specialties VALUES (default, 'Chirurgia laryngologiczna');
INSERT INTO specialties VALUES (default, 'Chirurgia naczyniowa');
INSERT INTO specialties VALUES (default, 'Chirurgia neurologiczna');
INSERT INTO specialties VALUES (default, 'Chirurgia ogólna i transplantacyjna');
INSERT INTO specialties VALUES (default, 'Chirurgia onkologiczna');
INSERT INTO specialties VALUES (default, 'Chirurgia ortopedyczna i traumatologiczna');
INSERT INTO specialties VALUES (default, 'Chirurgia plastyczna');
INSERT INTO specialties VALUES (default, 'Chirurgia szczękowo-twarzowa');
INSERT INTO specialties VALUES (default, 'Chirurgia stomatologiczna');
INSERT INTO specialties VALUES (default, 'Chirurgia stomatologiczna dziecięca');
INSERT INTO specialties VALUES (default, 'Dermatolog');
INSERT INTO specialties VALUES (default, 'Endokrynolog');
INSERT INTO specialties VALUES (default, 'Gastroenterolog');
INSERT INTO specialties VALUES (default, 'Ginekolog');
INSERT INTO specialties VALUES (default, 'Hematolog');
INSERT INTO specialties VALUES (default, 'Immunolog');
INSERT INTO specialties VALUES (default, 'Internista');
INSERT INTO specialties VALUES (default, 'Kardiolog');
INSERT INTO specialties VALUES (default, 'Kardiochirurg');
INSERT INTO specialties VALUES (default, 'Lekarz rodzinny');
INSERT INTO specialties VALUES (default, 'Medycyna pracy');
INSERT INTO specialties VALUES (default, 'Medycyna ratunkowa');
INSERT INTO specialties VALUES (default, 'Neonatolog');
INSERT INTO specialties VALUES (default, 'Nefrolog');
INSERT INTO specialties VALUES (default, 'Neurochirurg');
INSERT INTO specialties VALUES (default, 'Neurolog');
INSERT INTO specialties VALUES (default, 'Okulista');
INSERT INTO specialties VALUES (default, 'Onkolog');
INSERT INTO specialties VALUES (default, 'Ortopeda');
INSERT INTO specialties VALUES (default, 'Pediatra');
INSERT INTO specialties VALUES (default, 'Psychiatra');
INSERT INTO specialties VALUES (default, 'Pulmonolog');
INSERT INTO specialties VALUES (default, 'Radiolog');
INSERT INTO specialties VALUES (default, 'Radioterapeuta');
INSERT INTO specialties VALUES (default, 'Reumatolog');
INSERT INTO specialties VALUES (default, 'Stomatolog');
INSERT INTO specialties VALUES (default, 'Urolog');
INSERT INTO doc_specialties VALUES (1, 1);
INSERT INTO doc_specialties VALUES (2, 2);
INSERT INTO doc_specialties VALUES (3, 3);
INSERT INTO doc_specialties VALUES (4, 4);
INSERT INTO doc_specialties VALUES (5, 5);
INSERT INTO doc_specialties VALUES (6, 6);
INSERT INTO doc_specialties VALUES (7, 7);
INSERT INTO doc_specialties VALUES (8, 8);
INSERT INTO doc_specialties VALUES (9, 9);
INSERT INTO doc_specialties VALUES (10, 10);
INSERT INTO doc_specialties VALUES (11, 11);
INSERT INTO doc_specialties VALUES (12, 12);
INSERT INTO doc_specialties VALUES (13, 13);
INSERT INTO doc_specialties VALUES (14, 14);
INSERT INTO doc_specialties VALUES (15, 15);
INSERT INTO doc_specialties VALUES (16, 16);
INSERT INTO doc_specialties VALUES (17, 17);
INSERT INTO doc_specialties VALUES (18, 18);
INSERT INTO doc_specialties VALUES (19, 19);
INSERT INTO doc_specialties VALUES (20, 20);
INSERT INTO doc_specialties VALUES (21, 21);
INSERT INTO doc_specialties VALUES (22, 22);
INSERT INTO doc_specialties VALUES (23, 23);
INSERT INTO doc_specialties VALUES (24, 24);
INSERT INTO doc_specialties VALUES (25, 25);
INSERT INTO doc_specialties VALUES (26, 26);
INSERT INTO doc_specialties VALUES (27, 27);
INSERT INTO doc_specialties VALUES (28, 28);
INSERT INTO doc_specialties VALUES (29, 29);
INSERT INTO doc_specialties VALUES (30, 30);
INSERT INTO doc_specialties VALUES (31, 31);
INSERT INTO doc_specialties VALUES (32, 32);
INSERT INTO doc_specialties VALUES (33, 33);
INSERT INTO doc_specialties VALUES (34, 34);
INSERT INTO doc_specialties VALUES (35, 35);
INSERT INTO doc_specialties VALUES (36, 36);
INSERT INTO doc_specialties VALUES (37, 37);
INSERT INTO doc_specialties VALUES (38, 38);
INSERT INTO doc_specialties VALUES (39, 39);
INSERT INTO doc_specialties VALUES (40, 40);


INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Anna', 'Kowalska', '1978-07-15', 'Ul. Akademicka 123', 'Miastolandia', '123 456 789');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Jan', 'Nowak', '1955-12-03', 'Pl. Naukowy 456', 'Fantazjologia', ' 987 654 321');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Karolina', 'Michalska', '1982-09-10', 'Aleja Gwiezdna 789', 'AstroPlaneta', ' 555 444 333');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Adam', 'Nowicki', '1960-02-20', 'Ul. Technologiczna 234', 'Futuropolis', ' 777 888 999');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Ewa', 'Wójcik', '1974-05-07', 'Pl. Chemiczny 567', 'Nowa Era', ' 222 333 444');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Piotr', 'Lis', '1985-11-30', 'Ul. Naukowa 789', 'Sciencetown', ' 111 222 333');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Magdalena', 'Jaworska', '1990-06-20', 'Pl. Innowacji 234', 'Technopolis', ' 444 555 666');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Michał', 'Nowacki', '1972-04-03', 'Ul. Postępu 12', 'Progresowo', ' 777 888 999');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Alicja', 'Kowalczyk', '1988-09-17', 'Pl. Badań 34', 'Labolandia', ' 888 999 000');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Bartosz', 'Szymański', '1979-03-25', 'Ul. Wynalazków 56', 'Innovacity', ' 333 444 555');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Marlena', 'Wilk', '1983-08-12', 'Pl. Odkryć 78', 'Eureka', ' 666 777 888');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Karol', 'Kaczmarek', '1976-01-09', 'Ul. Naukowców 90', 'Geniusville', ' 222 333 444');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Elżbieta', 'Jankowska', '1992-07-04', 'Pl. Wynalazców 123', 'Inventopia', ' 777 888 999');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Wojciech', 'Duda', '1981-02-18', 'Ul. Techniczna 56', 'Innovationville', ' 444 555 666');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Dominika', 'Pawlak', '1987-05-23', 'Pl. Odkryć 89', 'Scienceland', ' 555 666 777');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Radosław', 'Górski', '1973-10-07', 'Ul. Badaczy 45', 'Exploratorium', ' 999 000 111');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Marta', 'Kamińska', '1980-12-15', 'Pl. Innowacji 67', 'Researchtown', ' 333 444 555');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Robert', 'Jastrzębski', '1984-09-28', 'Ul. Technologiczna 23', 'Techopolis', ' 666 777 888');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Katarzyna', 'Michałowska', '1991-06-14', 'Pl. Badań 78', 'Scientifica', ' 777 888 999');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Tomasz', 'Wojciechowski', '1977-03-02', 'Ul. Naukowców 45', 'Innovatopia', ' 888 999 000');
INSERT INTO patients (patient_id, first_name, last_name, birth_date, address, city, telephone) VALUES (default, 'Agnieszka', 'Piotrowska', '1989-08-27', 'Pl. Wynalazków 12', 'Inventoland', ' 000 111 222');
INSERT INTO visits VALUES (default, 7, '2013-01-01', 'mRNA shot');
INSERT INTO visits VALUES (default, 8, '2013-01-02', 'mRNA shot');
INSERT INTO visits VALUES (default, 8, '2013-01-03', 'mRNA shot');
INSERT INTO visits VALUES (default, 7, '2013-01-04', 'mRNA shot');
