DROP TABLE doc_specialties IF EXISTS;
DROP TABLE docs IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE patients IF EXISTS;


CREATE TABLE docs (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30)
);
CREATE INDEX docs_last_name ON docs (last_name);

CREATE TABLE specialties (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE doc_specialties (
  doc_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL
);
ALTER TABLE doc_specialties ADD CONSTRAINT fk_doc_specialties_vets FOREIGN KEY (doc_id) REFERENCES docs (id);
ALTER TABLE doc_specialties ADD CONSTRAINT fk_doc_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE patients (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER,
  first_name VARCHAR(30),
  last_name  VARCHAR_IGNORECASE(30),
  birth_date DATE,
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20)
);
CREATE INDEX patients_last_name ON patients (last_name);


CREATE TABLE visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id      INTEGER,
  visit_date  DATE,
  description VARCHAR(255)
);
ALTER TABLE visits ADD CONSTRAINT fk_visits_patients FOREIGN KEY (patient_id) REFERENCES patients (id);

CREATE INDEX visits_patient_id ON visits (patient_id);
